### ISSUE TITLE
Assistant : Error reading thread run response 

### ISSUE THREAD

**Issue by geoffreyfourmis** [TheoKanning/openai-java#412] opened 2023-11-17 09:23 UTC
Hello,

Using v0.18.1 just released with the #408 by @vacuityv , I was trying to run an assistant's thread (using function). Maybe I'm missing something but until now I'm unable de complete the run. 

Here is the code :
```java
        // Create thread with one message
        MessageRequest messageRequest = MessageRequest.builder()
                .content(text)
                .build();
        ThreadRequest threadRequest = ThreadRequest.builder()
                .messages(Collections.singletonList(messageRequest))
                .build();
        Thread thread = service.createThread(threadRequest);

        // run thread
        RunCreateRequest runCreateRequest = RunCreateRequest.builder()
                .assistantId(ASSISTANT_ID)
                .build();

        // error here
        Run run = service.createRun(thread.getId(), runCreateRequest);
```

Here is the error I got 
```
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.Class` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 25, column: 23] (through reference chain: com.theokanning.openai.runs.Run["tools"]->java.util.ArrayList[1]->com.theokanning.openai.assistants.Tool["function"]->com.theokanning.openai.completion.chat.ChatFunction["parameters"])
```
full stack trace :
[stack_trace.txt](https://github.com/TheoKanning/openai-java/files/13389490/stack_trace.txt)

If I manually call URLs here is the JSON response, like the stack trace says the pb is on tools->functions[1]->parameters
```json
{
    "id": "run_ID",
  (...)
    "tools": [
        {
            "type": "retrieval"
        },
        {
            "type": "function",
            "function": {
                "name": "function_test1",
                "description": "my description ",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "param_test1": {
                            "type": "string",
                            "description": "Param test1"
                        }
                    },
                    "required": [
                        "param_test1"
                    ]
                }
            }
        }
    ],
    (...)
}
```
full response :
[manual_call_response.json](https://github.com/TheoKanning/openai-java/files/13389727/manual_call_response.json)

In the source code I found that it is ChatFunction used : 
```java 
public class ChatFunction {
 (...)

    /**
     * The parameters the functions accepts.
     */
    @JsonProperty("parameters")
    private Class<?> parametersClass;
```

I'm trying to find the solution by myself, without success until now.

**Comment by vacuityv** [comment] 2023-11-17 09:46
I said the function part has something wrong but I am not sure. You can test without function call. It need to be fixed by the owner.发自我的 iPhone在 2023年11月17日，17:23，Geoffrey Fourmis ***@***.***> 写道：﻿
Hello,
Using v0.18.1 just released with the #408 by @vacuityv , I was trying to run an assistant's thread (using function). Maybe I'm missing something but until now I'm unable de complete the run.
Here is the code :
        // Create thread with one message
        MessageRequest messageRequest = MessageRequest.builder()
                .content(text)
                .build();
        ThreadRequest threadRequest = ThreadRequest.builder()
                .messages(Collections.singletonList(messageRequest))
                .build();
        Thread thread = service.createThread(threadRequest);

        // run thread
        RunCreateRequest runCreateRequest = RunCreateRequest.builder()
                .assistantId(ASSISTANT_ID)
                .build();

        // error here
        Run run = service.createRun(thread.getId(), runCreateRequest);
Here is the error I got
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.Class` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 25, column: 23] (through reference chain: com.theokanning.openai.runs.Run["tools"]->java.util.ArrayList[1]->com.theokanning.openai.assistants.Tool["function"]->com.theokanning.openai.completion.chat.ChatFunction["parameters"])

full stack trace :
stack_trace.txt
If I manually call URLs here is the JSON I receive, like the stack stace says the pb is on tools->functions[1]->parameters
{
    "id": "run_ID",
  (...)
    "tools": [
        {
            "type": "retrieval"
        },
        {
            "type": "function",
            "function": {
                "name": "function_test1",
                "description": "my description ",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "param_test1": {
                            "type": "string",
                            "description": "Param test1"
                        }
                    },
                    "required": [
                        "param_test1"
                    ]
                }
            }
        }
    ],
    (...)
}
full response :
manual_call_response.json
In the source code I found that it is ChatFunction used :
public class ChatFunction {
 (...)

    /**
     * The parameters the functions accepts.
     */
    @JsonProperty("parameters")
    private Class<?> parametersClass;
I'm trying to find the solution by myself, without success until now.

**Comment by vacuityv** [comment] 2023-11-17 10:00
Or I will test it tonight发自我的 iPhone在 2023年11月17日，17:45，彭伟 ***@***.***> 写道：﻿I said the function part has something wrong but I am not sure. You can test without function call. It need to be fixed by the owner.发自我的 iPhone在 2023年11月17日，17:23，Geoffrey Fourmis ***@***.***> 写道：﻿
Hello,
Using v0.18.1 just released with the #408 by @vacuityv , I was trying to run an assistant's thread (using function). Maybe I'm missing something but until now I'm unable de complete the run.
Here is the code :
        // Create thread with one message
        MessageRequest messageRequest = MessageRequest.builder()
                .content(text)
                .build();
        ThreadRequest threadRequest = ThreadRequest.builder()
                .messages(Collections.singletonList(messageRequest))
                .build();
        Thread thread = service.createThread(threadRequest);

        // run thread
        RunCreateRequest runCreateRequest = RunCreateRequest.builder()
                .assistantId(ASSISTANT_ID)
                .build();

        // error here
        Run run = service.createRun(thread.getId(), runCreateRequest);
Here is the error I got
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.Class` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 25, column: 23] (through reference chain: com.theokanning.openai.runs.Run["tools"]->java.util.ArrayList[1]->com.theokanning.openai.assistants.Tool["function"]->com.theokanning.openai.completion.chat.ChatFunction["parameters"])

full stack trace :
stack_trace.txt
If I manually call URLs here is the JSON I receive, like the stack stace says the pb is on tools->functions[1]->parameters
{
    "id": "run_ID",
  (...)
    "tools": [
        {
            "type": "retrieval"
        },
        {
            "type": "function",
            "function": {
                "name": "function_test1",
                "description": "my description ",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "param_test1": {
                            "type": "string",
                            "description": "Param test1"
                        }
                    },
                    "required": [
                        "param_test1"
                    ]
                }
            }
        }
    ],
    (...)
}
full response :
manual_call_response.json
In the source code I found that it is ChatFunction used :
public class ChatFunction {
 (...)

    /**
     * The parameters the functions accepts.
     */
    @JsonProperty("parameters")
    private Class<?> parametersClass;
I'm trying to find the solution by myself, without success until now.

**Comment by geoffreyfourmis** [comment] 2023-11-17 11:04
Thanks you for the quick answers, I just tried using the simple weather function example from Open AI assistant and I got the same error.

I was able to complete the call localy & temporary by ignoring the property `parameters` in `ChatFunction`
```java
@JsonIgnoreProperties(value={ "parameters" })
public class ChatFunction {
```

Because I don't understand how jackson is suppose de deserailize this : 
```java
    @JsonProperty("parameters")
    private Class<?> parametersClass;
```

**Comment by vacuityv** [comment] 2023-11-17 14:28
@geoffreyfourmis  I checked and it's because the function is different from the chat-function. I said here:

https://github.com/TheoKanning/openai-java/issues/390

<img width="999" alt="image" src="https://github.com/TheoKanning/openai-java/assets/13598237/d8a60c6e-b7bb-4f10-82ee-7fe42a355edb">
<img width="1034" alt="image" src="https://github.com/TheoKanning/openai-java/assets/13598237/2e44c289-85a0-4c1f-88a9-378a9aa2ddf3">

And I think it nned to be fixed by @TheoKanning

**Comment by vacuityv** [comment] 2023-11-20 03:05
@geoffreyfourmis  I make a pr for this: https://github.com/TheoKanning/openai-java/pull/415. You can get more infomation about function in this file: AssistantFunctionTest. And we need @TheoKanning  to review and merge it.

**Comment by TheoKanning** [comment] 2023-11-21 00:41
Fixed in 0.18.2

**Closed by TheoKanning** 2023-11-21 00:41 UTC

**Comment by geoffreyfourmis** [comment] 2023-11-21 07:28
Thanks both of you, it's working great

**Comment by vacuityv** [comment] 2023-11-21 07:52
@geoffreyfourmis  Happy that was fixed. You are welcome.
